name: AzureLoginSample

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
    - name: Retrieve secret
      id: retrieve-secret
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'keyvaultleo666' 
        secrets: 'env2'

    - name: Print Secret Value
      run: echo "${{ steps.retrieve-secret.outputs.env2 }}"
